image: 836525813842.dkr.ecr.us-east-1.amazonaws.com/jmeter-plugins-build:1.2

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  XTN5250_VERSION: 1.19m
  DM3270_VERSION: 0.5-beta-37

cache:
  paths:
    - .m2/repository/
    - .jmeter/
before_script:
  - set -e
  - /install-maven-dependency.sh https://sourceforge.net/projects/xtn5250/files/xtn5250/$XTN5250_VERSION/xtn5250_${XTN5250_VERSION//.}.jar net.sourceforge.xtn5250 xtn5250 $XTN5250_VERSION
  - /install-maven-dependency.sh https://github.com/dmolony/dm3270/releases/download/v$DM3270_VERSION/dm3270.jar com.bytezone.dm3270 dm3270 $DM3270_VERSION
build:
  stage: build
  tags:
    - docker
  except:
    - master
  script: /execute-on-vnc.sh mvn --batch-mode clean install
  artifacts:
    paths:
      - target/jmeter-bzm-rte-*.jar
      - target/jmeter-test
    expire_in: 1 month
build_and_analyze:
  stage: build
  tags:
    - docker
  only:
    - master
  script: /execute-on-vnc.sh mvn --batch-mode -Psonar clean install sonar:sonar -Dsonar.host.url=http://sonar.abstracta.us -Dsonar.login=$SONAR_TOKEN
  artifacts:
    paths:
      - target/jmeter-bzm-rte-*.jar
      - target/jmeter-test
    expire_in: 1 month
jmeter_compatibility:
  stage: test
  tags:
    - docker
  script:
    - cd target/jmeter-test
    - sh testJMeter.sh 4.0
    - sh testJMeter.sh 3.3
    - sh testJMeter.sh 3.2
    - sh testJMeter.sh 3.1
    - bzt testJMeterBZ.yaml
  artifacts:
    when: on_failure
    paths:
      - target/jmeter-test
    expire_in: 4 hour
release:
  stage: deploy
  tags:
    - docker
  only:
    - master
  when: manual
  script: /release.sh
  artifacts:
    paths:
      - target/jmeter-bzm-rte-*.jar