name: publish release
on:
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: blazemeter_test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get version
        id: version
        run: echo "release_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Check version
        run: .github/semver-check.sh ${{ env.release_version }}
      - name: set maven project version
        run: mvn --batch-mode --no-transfer-progress versions:set -DnewVersion=${{ env.release_version }} --settings .github/settings.xml
      - name: package release
        run: mvn --batch-mode --no-transfer-progress clean package --settings .github/settings.xml
      - name: Upload built jar into release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          file_glob: true
          tag: ${{ github.ref }}
      - name: publish to Nexus
        run: .github/maven-central-deploy.sh
        env:
          GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
          GPG_EXECUTABLE: gpg
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: update Readme version
        run: |-
          sed -i "s/<version>.*<\/version>/<version>${GITHUB_REF#refs/tags/v}<\/version>/g" README.md
          git add README.md
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git commit -m "[skip ci] Updated README"
          git push origin HEAD:master
